services:
  web:
    environment:
      SECRET_KEY: "REEMPLAZAME_EN_PROD"
      DEBUG: "0"
      DATABASE_ENGINE: "postgres"
      POSTGRES_DB: domipyme
      POSTGRES_USER: domipyme
      POSTGRES_PASSWORD: domipyme
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      FRONTEND_BASE_URL: "http://localhost:5173"
      EMAIL_BACKEND: "smtp"
      EMAIL_HOST: "smtp.sendgrid.net"
      EMAIL_PORT: "587"
      EMAIL_USE_TLS: "1"
      EMAIL_HOST_USER: "apikey"
      EMAIL_HOST_PASSWORD: "YOUR_SENDGRID_API_KEY"
      DEFAULT_FROM_EMAIL: "no-reply@domipyme.com"
