# Generated by Django 4.2.26 on 2025-11-14 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="monthly_fee_active",
        ),
    ]
