# Generated by Django 4.2.26 on 2025-11-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
