# Generated by Django 4.2.26 on 2025-12-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0002_shop_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
