# Generated by Django 4.2.26 on 2025-12-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0004_alter_category_options_category_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/gallery/%Y/%m/")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Texto alternativo para accesibilidad",
                        max_length=255,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Imagen principal del producto"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Orden de visualización (menor primero)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shops.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "order"],
                        name="shops_produ_product_802aa8_idx",
                    ),
                    models.Index(
                        fields=["product", "is_primary"],
                        name="shops_produ_product_4f9715_idx",
                    ),
                ],
            },
        ),
    ]
