# Generated by Django 4.2.26 on 2025-12-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_cart_cartitem_cart_orders_cart_user_id_3e98b6_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("mercadopago", "MercadoPago"),
                            ("paypal", "PayPal"),
                            ("cash", "Cash"),
                        ],
                        default="stripe",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "stripe_client_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "payment_data",
                    models.JSONField(
                        blank=True,
                        help_text="Datos adicionales del proveedor de pago",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "-created_at"],
                        name="orders_paym_order_i_ee6c4b_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="orders_paym_status_5b2895_idx",
                    ),
                    models.Index(
                        fields=["stripe_payment_intent_id"],
                        name="orders_paym_stripe__40efb1_idx",
                    ),
                ],
            },
        ),
    ]
