# Generated by Django 4.2.26 on 2025-11-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                (
                    "provider_tx_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.CharField(max_length=50)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
