# Generated by Django 4.2.26 on 2025-12-03 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_options_remove_user_date_joined_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_created", "Nueva Orden"),
                            ("order_status_changed", "Estado de Orden Cambiado"),
                            ("low_stock", "Stock Bajo"),
                            ("new_review", "Nueva Reseña"),
                            ("payment_received", "Pago Recibido"),
                            ("shop_approved", "Tienda Aprobada"),
                            ("shop_rejected", "Tienda Rechazada"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Tipo de Notificación",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensaje")),
                ("read", models.BooleanField(default=False, verbose_name="Leída")),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="URL relativa dentro de la app (ej: /orders/123)",
                        max_length=500,
                        null=True,
                        verbose_name="URL de Enlace",
                    ),
                ),
                (
                    "order_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de Orden"
                    ),
                ),
                (
                    "shop_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de Tienda"
                    ),
                ),
                (
                    "product_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de Producto"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_no_user_id_b37b35_idx",
                    ),
                    models.Index(
                        fields=["user", "read"], name="accounts_no_user_id_1df518_idx"
                    ),
                ],
            },
        ),
    ]
